// <auto-generated />
using System;
using HireThemNoW.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HireThemNoW.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251002182634_AddReleaseNote_1_1_2")]
    partial class AddReleaseNote_1_1_2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HireThemNoW.Server.Models.EmailPreference", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MarketingEmails")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("WeeklyPerformanceReport")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("EmailPreferences");
                });

            modelBuilder.Entity("HireThemNoW.Server.Models.Industry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Industries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Technology"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Healthcare"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Education"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Sales"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Manufacturing"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Retail"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Hospitality"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Construction"
                        });
                });

            modelBuilder.Entity("HireThemNoW.Server.Models.ReleaseNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("ReleaseNotes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Features = "[\"Added Privacy Controls (Profile Visibility \\u0026 Analytics)\",\"Implemented Data Export functionality\",\"Added Account Deletion feature\",\"Fixed CORS issues with Industries endpoint\",\"Added top navbar with search and notifications\",\"Implemented notification badge showing trial days remaining\"]",
                            IsPublished = true,
                            ReleaseDate = new DateTime(2025, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Version = "1.2.0"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Features = "[\"Email preferences management\",\"Profile update functionality\",\"Resume upload and download\",\"Trial period tracking\",\"User onboarding flow\"]",
                            IsPublished = true,
                            ReleaseDate = new DateTime(2025, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Version = "1.1.0"
                        });
                });

            modelBuilder.Entity("HireThemNoW.Server.Models.ResumeAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AtsAchievementsScore")
                        .HasColumnType("integer")
                        .HasColumnName("ats_achievements_score");

                    b.Property<int?>("AtsEducationScore")
                        .HasColumnType("integer")
                        .HasColumnName("ats_education_score");

                    b.Property<int?>("AtsExperienceScore")
                        .HasColumnType("integer")
                        .HasColumnName("ats_experience_score");

                    b.Property<int?>("AtsFormattingScore")
                        .HasColumnType("integer")
                        .HasColumnName("ats_formatting_score");

                    b.Property<int?>("AtsKeywordsScore")
                        .HasColumnType("integer")
                        .HasColumnName("ats_keywords_score");

                    b.Property<int?>("AtsOverallScore")
                        .HasColumnType("integer")
                        .HasColumnName("ats_overall_score");

                    b.Property<int?>("AtsSkillsScore")
                        .HasColumnType("integer")
                        .HasColumnName("ats_skills_score");

                    b.Property<string>("Certifications")
                        .HasColumnType("text")
                        .HasColumnName("certifications");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Education")
                        .HasColumnType("text")
                        .HasColumnName("education");

                    b.Property<string>("ExperienceSummary")
                        .HasColumnType("text")
                        .HasColumnName("experience_summary");

                    b.Property<string>("Improvements")
                        .HasColumnType("text")
                        .HasColumnName("improvements");

                    b.Property<int?>("KeywordDensity")
                        .HasColumnType("integer")
                        .HasColumnName("keyword_density");

                    b.Property<string>("KeywordsFound")
                        .HasColumnType("text")
                        .HasColumnName("keywords_found");

                    b.Property<string>("KeywordsMissing")
                        .HasColumnType("text")
                        .HasColumnName("keywords_missing");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("ProgrammingLanguages")
                        .HasColumnType("text")
                        .HasColumnName("programming_languages");

                    b.Property<string>("ReadabilityIssues")
                        .HasColumnType("text")
                        .HasColumnName("readability_issues");

                    b.Property<int?>("ReadabilityScore")
                        .HasColumnType("integer")
                        .HasColumnName("readability_score");

                    b.Property<string>("Recommendations")
                        .HasColumnType("text")
                        .HasColumnName("recommendations");

                    b.Property<string>("ResumeUrl")
                        .HasColumnType("text")
                        .HasColumnName("resume_url");

                    b.Property<string>("S3Url")
                        .HasColumnType("text")
                        .HasColumnName("s3_url");

                    b.Property<string>("SoftSkills")
                        .HasColumnType("text")
                        .HasColumnName("soft_skills");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Strengths")
                        .HasColumnType("text")
                        .HasColumnName("strengths");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("TechnicalSkills")
                        .HasColumnType("text")
                        .HasColumnName("technical_skills");

                    b.Property<string>("Tools")
                        .HasColumnType("text")
                        .HasColumnName("tools");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("Weaknesses")
                        .HasColumnType("text")
                        .HasColumnName("weaknesses");

                    b.Property<int?>("YearsOfExperience")
                        .HasColumnType("integer")
                        .HasColumnName("years_of_experience");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("resume_analyses");
                });

            modelBuilder.Entity("HireThemNoW.Server.Models.SkillExpertise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IndustryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("IndustryId");

                    b.ToTable("SkillExpertises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IndustryId = 1,
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = 2,
                            IndustryId = 1,
                            Name = "Python"
                        },
                        new
                        {
                            Id = 3,
                            IndustryId = 1,
                            Name = "React"
                        },
                        new
                        {
                            Id = 4,
                            IndustryId = 1,
                            Name = "Node.js"
                        },
                        new
                        {
                            Id = 5,
                            IndustryId = 1,
                            Name = "TypeScript"
                        },
                        new
                        {
                            Id = 6,
                            IndustryId = 1,
                            Name = "C#"
                        },
                        new
                        {
                            Id = 7,
                            IndustryId = 1,
                            Name = "Java"
                        },
                        new
                        {
                            Id = 8,
                            IndustryId = 1,
                            Name = "SQL"
                        },
                        new
                        {
                            Id = 9,
                            IndustryId = 1,
                            Name = "AWS"
                        },
                        new
                        {
                            Id = 10,
                            IndustryId = 1,
                            Name = "Docker"
                        },
                        new
                        {
                            Id = 11,
                            IndustryId = 1,
                            Name = "Kubernetes"
                        },
                        new
                        {
                            Id = 12,
                            IndustryId = 1,
                            Name = "DevOps"
                        },
                        new
                        {
                            Id = 13,
                            IndustryId = 1,
                            Name = "Machine Learning"
                        },
                        new
                        {
                            Id = 14,
                            IndustryId = 1,
                            Name = "Data Science"
                        },
                        new
                        {
                            Id = 15,
                            IndustryId = 1,
                            Name = "Cybersecurity"
                        },
                        new
                        {
                            Id = 16,
                            IndustryId = 2,
                            Name = "Financial Analysis"
                        },
                        new
                        {
                            Id = 17,
                            IndustryId = 2,
                            Name = "Accounting"
                        },
                        new
                        {
                            Id = 18,
                            IndustryId = 2,
                            Name = "Risk Management"
                        },
                        new
                        {
                            Id = 19,
                            IndustryId = 2,
                            Name = "Investment Banking"
                        },
                        new
                        {
                            Id = 20,
                            IndustryId = 2,
                            Name = "Portfolio Management"
                        },
                        new
                        {
                            Id = 21,
                            IndustryId = 2,
                            Name = "Financial Modeling"
                        },
                        new
                        {
                            Id = 22,
                            IndustryId = 2,
                            Name = "Excel"
                        },
                        new
                        {
                            Id = 23,
                            IndustryId = 2,
                            Name = "QuickBooks"
                        },
                        new
                        {
                            Id = 24,
                            IndustryId = 2,
                            Name = "Tax Preparation"
                        },
                        new
                        {
                            Id = 25,
                            IndustryId = 2,
                            Name = "Auditing"
                        },
                        new
                        {
                            Id = 26,
                            IndustryId = 3,
                            Name = "Patient Care"
                        },
                        new
                        {
                            Id = 27,
                            IndustryId = 3,
                            Name = "Medical Coding"
                        },
                        new
                        {
                            Id = 28,
                            IndustryId = 3,
                            Name = "Nursing"
                        },
                        new
                        {
                            Id = 29,
                            IndustryId = 3,
                            Name = "EMR Systems"
                        },
                        new
                        {
                            Id = 30,
                            IndustryId = 3,
                            Name = "Healthcare Administration"
                        },
                        new
                        {
                            Id = 31,
                            IndustryId = 3,
                            Name = "Medical Terminology"
                        },
                        new
                        {
                            Id = 32,
                            IndustryId = 3,
                            Name = "HIPAA Compliance"
                        },
                        new
                        {
                            Id = 33,
                            IndustryId = 3,
                            Name = "Clinical Research"
                        },
                        new
                        {
                            Id = 34,
                            IndustryId = 3,
                            Name = "Pharmacy"
                        },
                        new
                        {
                            Id = 35,
                            IndustryId = 3,
                            Name = "Physical Therapy"
                        },
                        new
                        {
                            Id = 36,
                            IndustryId = 4,
                            Name = "Curriculum Development"
                        },
                        new
                        {
                            Id = 37,
                            IndustryId = 4,
                            Name = "Classroom Management"
                        },
                        new
                        {
                            Id = 38,
                            IndustryId = 4,
                            Name = "Educational Technology"
                        },
                        new
                        {
                            Id = 39,
                            IndustryId = 4,
                            Name = "Lesson Planning"
                        },
                        new
                        {
                            Id = 40,
                            IndustryId = 4,
                            Name = "Student Assessment"
                        },
                        new
                        {
                            Id = 41,
                            IndustryId = 4,
                            Name = "Online Teaching"
                        },
                        new
                        {
                            Id = 42,
                            IndustryId = 4,
                            Name = "Special Education"
                        },
                        new
                        {
                            Id = 43,
                            IndustryId = 4,
                            Name = "Tutoring"
                        },
                        new
                        {
                            Id = 44,
                            IndustryId = 4,
                            Name = "Academic Advising"
                        },
                        new
                        {
                            Id = 45,
                            IndustryId = 4,
                            Name = "Educational Psychology"
                        },
                        new
                        {
                            Id = 46,
                            IndustryId = 5,
                            Name = "Digital Marketing"
                        },
                        new
                        {
                            Id = 47,
                            IndustryId = 5,
                            Name = "SEO"
                        },
                        new
                        {
                            Id = 48,
                            IndustryId = 5,
                            Name = "Content Marketing"
                        },
                        new
                        {
                            Id = 49,
                            IndustryId = 5,
                            Name = "Social Media Marketing"
                        },
                        new
                        {
                            Id = 50,
                            IndustryId = 5,
                            Name = "Email Marketing"
                        },
                        new
                        {
                            Id = 51,
                            IndustryId = 5,
                            Name = "Google Analytics"
                        },
                        new
                        {
                            Id = 52,
                            IndustryId = 5,
                            Name = "Brand Management"
                        },
                        new
                        {
                            Id = 53,
                            IndustryId = 5,
                            Name = "Market Research"
                        },
                        new
                        {
                            Id = 54,
                            IndustryId = 5,
                            Name = "Copywriting"
                        },
                        new
                        {
                            Id = 55,
                            IndustryId = 5,
                            Name = "PPC Advertising"
                        },
                        new
                        {
                            Id = 56,
                            IndustryId = 6,
                            Name = "B2B Sales"
                        },
                        new
                        {
                            Id = 57,
                            IndustryId = 6,
                            Name = "B2C Sales"
                        },
                        new
                        {
                            Id = 58,
                            IndustryId = 6,
                            Name = "CRM Software"
                        },
                        new
                        {
                            Id = 59,
                            IndustryId = 6,
                            Name = "Lead Generation"
                        },
                        new
                        {
                            Id = 60,
                            IndustryId = 6,
                            Name = "Negotiation"
                        },
                        new
                        {
                            Id = 61,
                            IndustryId = 6,
                            Name = "Account Management"
                        },
                        new
                        {
                            Id = 62,
                            IndustryId = 6,
                            Name = "Sales Strategy"
                        },
                        new
                        {
                            Id = 63,
                            IndustryId = 6,
                            Name = "Cold Calling"
                        },
                        new
                        {
                            Id = 64,
                            IndustryId = 6,
                            Name = "Salesforce"
                        },
                        new
                        {
                            Id = 65,
                            IndustryId = 6,
                            Name = "Customer Relationship"
                        },
                        new
                        {
                            Id = 66,
                            IndustryId = 7,
                            Name = "Quality Control"
                        },
                        new
                        {
                            Id = 67,
                            IndustryId = 7,
                            Name = "Lean Manufacturing"
                        },
                        new
                        {
                            Id = 68,
                            IndustryId = 7,
                            Name = "Six Sigma"
                        },
                        new
                        {
                            Id = 69,
                            IndustryId = 7,
                            Name = "Production Planning"
                        },
                        new
                        {
                            Id = 70,
                            IndustryId = 7,
                            Name = "Supply Chain Management"
                        },
                        new
                        {
                            Id = 71,
                            IndustryId = 7,
                            Name = "CAD/CAM"
                        },
                        new
                        {
                            Id = 72,
                            IndustryId = 7,
                            Name = "Process Improvement"
                        },
                        new
                        {
                            Id = 73,
                            IndustryId = 7,
                            Name = "Safety Compliance"
                        },
                        new
                        {
                            Id = 74,
                            IndustryId = 7,
                            Name = "Inventory Management"
                        },
                        new
                        {
                            Id = 75,
                            IndustryId = 7,
                            Name = "Equipment Maintenance"
                        },
                        new
                        {
                            Id = 76,
                            IndustryId = 8,
                            Name = "Customer Service"
                        },
                        new
                        {
                            Id = 77,
                            IndustryId = 8,
                            Name = "Merchandising"
                        },
                        new
                        {
                            Id = 78,
                            IndustryId = 8,
                            Name = "Point of Sale (POS)"
                        },
                        new
                        {
                            Id = 79,
                            IndustryId = 8,
                            Name = "Visual Merchandising"
                        },
                        new
                        {
                            Id = 80,
                            IndustryId = 8,
                            Name = "Store Management"
                        },
                        new
                        {
                            Id = 81,
                            IndustryId = 8,
                            Name = "Retail Analytics"
                        },
                        new
                        {
                            Id = 82,
                            IndustryId = 8,
                            Name = "Loss Prevention"
                        },
                        new
                        {
                            Id = 83,
                            IndustryId = 8,
                            Name = "Cash Handling"
                        },
                        new
                        {
                            Id = 84,
                            IndustryId = 8,
                            Name = "Product Knowledge"
                        },
                        new
                        {
                            Id = 85,
                            IndustryId = 8,
                            Name = "E-commerce"
                        },
                        new
                        {
                            Id = 86,
                            IndustryId = 9,
                            Name = "Guest Relations"
                        },
                        new
                        {
                            Id = 87,
                            IndustryId = 9,
                            Name = "Hotel Management"
                        },
                        new
                        {
                            Id = 88,
                            IndustryId = 9,
                            Name = "Food Service"
                        },
                        new
                        {
                            Id = 89,
                            IndustryId = 9,
                            Name = "Event Planning"
                        },
                        new
                        {
                            Id = 90,
                            IndustryId = 9,
                            Name = "Housekeeping Management"
                        },
                        new
                        {
                            Id = 91,
                            IndustryId = 9,
                            Name = "Front Desk Operations"
                        },
                        new
                        {
                            Id = 92,
                            IndustryId = 9,
                            Name = "Culinary Arts"
                        },
                        new
                        {
                            Id = 93,
                            IndustryId = 9,
                            Name = "Bartending"
                        },
                        new
                        {
                            Id = 94,
                            IndustryId = 9,
                            Name = "Tourism"
                        },
                        new
                        {
                            Id = 95,
                            IndustryId = 9,
                            Name = "Reservation Systems"
                        },
                        new
                        {
                            Id = 96,
                            IndustryId = 10,
                            Name = "Project Management"
                        },
                        new
                        {
                            Id = 97,
                            IndustryId = 10,
                            Name = "Blueprint Reading"
                        },
                        new
                        {
                            Id = 98,
                            IndustryId = 10,
                            Name = "Carpentry"
                        },
                        new
                        {
                            Id = 99,
                            IndustryId = 10,
                            Name = "Electrical Work"
                        },
                        new
                        {
                            Id = 100,
                            IndustryId = 10,
                            Name = "Plumbing"
                        },
                        new
                        {
                            Id = 101,
                            IndustryId = 10,
                            Name = "OSHA Compliance"
                        },
                        new
                        {
                            Id = 102,
                            IndustryId = 10,
                            Name = "Estimating"
                        },
                        new
                        {
                            Id = 103,
                            IndustryId = 10,
                            Name = "Heavy Equipment Operation"
                        },
                        new
                        {
                            Id = 104,
                            IndustryId = 10,
                            Name = "Welding"
                        },
                        new
                        {
                            Id = 105,
                            IndustryId = 10,
                            Name = "Site Supervision"
                        });
                });

            modelBuilder.Entity("HireThemNoW.Server.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("AllowAnalyticsDataSharing")
                        .HasColumnType("boolean");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Experience")
                        .HasColumnType("text");

                    b.Property<bool>("HasActiveSubscription")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasSeenTrialEndMessage")
                        .HasColumnType("boolean");

                    b.Property<string>("Industry")
                        .HasColumnType("text");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTrialActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Picture")
                        .HasColumnType("text");

                    b.Property<string>("ProfileVisibility")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResumeUrl")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTime>("TrialEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("TrialStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HireThemNoW.Server.Models.EmailPreference", b =>
                {
                    b.HasOne("HireThemNoW.Server.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("HireThemNoW.Server.Models.EmailPreference", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HireThemNoW.Server.Models.ResumeAnalysis", b =>
                {
                    b.HasOne("HireThemNoW.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HireThemNoW.Server.Models.SkillExpertise", b =>
                {
                    b.HasOne("HireThemNoW.Server.Models.Industry", "Industry")
                        .WithMany("Skills")
                        .HasForeignKey("IndustryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Industry");
                });

            modelBuilder.Entity("HireThemNoW.Server.Models.Industry", b =>
                {
                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
